# Generated by Django 4.1.5 on 2023-03-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMDev_app', '0003_producto_nombre_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=20),
        ),
    ]
