# Generated by Django 4.1.5 on 2023-03-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMDev_app', '0005_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=False, upload_to='WebMDev_app/static/WebMDev_app/assets/img'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.FloatField(default=0.0),
        ),
    ]
