# Generated by Django 4.1.5 on 2023-03-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMDev_app', '0008_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=40)),
                ('password2', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=40)),
                ('password2', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
