# Generated by Django 4.1.5 on 2023-03-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebMDev_app', '0013_rename_descripcion_compra_envio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserCreationForm',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
