# Generated by Django 4.1.7 on 2023-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMDev_app', '0018_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
