# Generated by Django 4.1.7 on 2023-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMDev_app', '0020_alter_producto_precio_alter_producto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='user',
        ),
        migrations.AddField(
            model_name='producto',
            name='userName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
